Migrate to pytest
cloudinary/pycloudinary pull request #376
Opened 2023-10-26 13:31 UTC by kurayami07734

### Brief Summary of Changes
edited the test command in tox.ini and include pytest in setup.py

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [x] Refactoring
- [ ] New feature
- [ ] Bug fix
- [ ] Adds more tests

#### Reviewer, please note:

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

2023-10-26 13:50 UTC, kurayami07734 commented
How do I include pytest as a dependency?

2023-10-26 14:26 UTC, const-cloudinary requested changes

2023-10-26 14:26 UTC, const-cloudinary commented on tox.ini
> +  core: python setup.py && python -m pytest test
According to:
https://docs.pytest.org/en/7.1.x/how-to/usage.html#calling-pytest-through-python-m-pytest

the command should be:
`python -m pytest test` 
without `python setup.py &&` part

2024-10-06 11:01 UTC, const-cloudinary approved these changes

2024-10-06 11:01 UTC, const-cloudinary commented on tox.ini
> +  core: python setup.py && python -m pytest test
```suggestion
  core: python -m pytest test 
```

2024-10-07 17:11 UTC, const-cloudinary commented
Fixed in #404

2024-10-07 17:11 UTC, closed without merging